version: 2.1

executors:
  node-alpine:
    docker:
      - image: node:alpine
  alpine:
    docker:
      - image: alpine:latest

jobs:
  index:
    executor: node-alpine
    steps:
      - checkout
      - run: mkdir /data
      - run: apk add git
      - run: npm ci && npm run fetch:vcpkg && npm run make:index
      - run: cp ./vcpkg-index.nedb /data/
      - persist_to_workspace:
          root: /data
          paths:
            - vcpkg-index.nedb

  build:
    executor: node-alpine
    environment:
      # configure custom pages domain and base url
      PAGES_CUSTOM_DOMAIN: vcpkg.dev
      BASE_URL: /
    steps:
      - checkout
      - attach_workspace:
          at: /data
      - run: mkdir -p ./app/public/db && mv /data/vcpkg-index.nedb ./app/public/db/vcpkg-index.nedb
      - run:
          working_directory: ./app
          command: |
              npm ci &&
              npm run make:dbfs &&
              NODE_ENV=production npm run build &&
              cp ./dist/index.html ./dist/404.html &&
              [[ ! -z $PAGES_CUSTOM_DOMAIN ]] && echo "$PAGES_CUSTOM_DOMAIN" > ./dist/CNAME
      - run: |
          cp -r ./app/dist/ /data/
      - persist_to_workspace:
          root: /data
          paths:
            - dist/

  dist:
    executor: alpine
    steps:
      - attach_workspace:
          at: /data
      - add_ssh_keys:
          fingerprints:
            - "15:29:09:82:7c:91:e1:5e:3d:75:be:d4:53:10:57:bf"
      # adding github.com to known host without checking is dangerous!
      # considered ok, as data is not sensitive
      - run: |
          apk add git openssh &&
          ssh-keyscan github.com >> ~/.ssh/known_hosts &&
          git config --global user.email "ci-build@vcpkg-index.git" &&
          git config --global user.name "ci-build"
      - run:
          working_directory: /data/dist
          command: |
              git init &&
              git add -A &&
              git commit -m "[ci skip] deploy $(date -uIseconds)" &&
              git push -f git@github.com:bitmeal/vcpkg-index.git master:gh-pages

workflows:
  cron:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - index
      - build:
          requires:
              - index
      - dist:
          requires:
              - build

  commit:
    jobs:
      - index:
          filters:
              branches:
                  only:
                    - master
      - build:
          requires:
              - index
          filters:
              branches:
                  only:
                    - master
      - dist:
          requires:
              - build
          filters:
              branches:
                  only:
                    - master
