version: 2.1

executors:
  node-alpine:
    docker:
      - image: node:alpine
  alpine:
    docker:
      - image: alpine:latest

jobs:
  index:
    executor: node-alpine
    steps:
      - checkout
      - run: mkdir /data
      - run: apk add git
      - run: npm install && npm run fetch-vcpkg && npm run make-index
      - run: cp ./vcpkg-index.json /data/
      - persist_to_workspace:
          root: /data
          paths:
            - vcpkg-index.json

  build:
    executor: node-alpine
    steps:
      - checkout
      - attach_workspace:
          at: /data
      - run: cp /data/vcpkg-index.json ./
      - run:
          working_directory: ./app
          command: npm install && npm run build
      - run: cp -r ./app/dist/ /data/
      - persist_to_workspace:
          root: /data
          paths:
            - dist/

  dist:
    executor: alpine
    steps:
      - attach_workspace:
          at: /data
      - add_ssh_keys:
          fingerprints:
            - "15:29:09:82:7c:91:e1:5e:3d:75:be:d4:53:10:57:bf"
      - run: |
          apk add git &&
          git config --global user.email "ci-build@vcpkg-index.git" &&
          git config --global user.name "ci-build"
      - run:
          working_directory: /data/dist
          command: |
              git init &&
              git add -A &&
              git commit -m 'deploy' &&
              git push -f git@github.com:bitmeal/vcpkg-index.git master:gh-pages

workflows:
  app:
    jobs:
      - index
      - build:
          requires:
              - index
      - dist:
          requires:
              - build
